#!/bin/sh
set -eu

: ${DESTDIR:=}
: ${PREFIX:=/usr/local}

cd "$(dirname "$0")"

install -Dv -m 755 qemu.initd "$DESTDIR"/etc/init.d/qemu
install -Dv -m 644 qemu.confd "$DESTDIR"/etc/conf.d/qemu
install -Dv -m 755 qemush "${DESTDIR}${PREFIX}"/bin/qemush
