#!/bin/sh
# vim: set ts=4:

if [ -z "$1" ]; then
	echo "Usage: virsh <VM-NAME | SOCKET-PATH> [command ...]" 1>&2
	exit 1
fi

case "$1" in
	/*) socket_path="$1" ;;
	*) socket_path="/run/qemu/$1/monitor.sock" ;;
esac

if [ ! -S "$socket_path" ]; then
	echo "Error: QEMU monitor socket $socket_path does not exist!" 1>&2
	exit 2
fi

if [ -n "$2" ]; then
	IFS=$'\n'
	shift
	echo -e "$*" | socat - "UNIX-CONNECT:$socket_path"
else
	echo 'Connecting to QEMU monitor in interactive mode. Use Ctrl+O to exit.'
	echo 'Note: command "quit" does not exit the monitor, but stops VM!'
	echo ''
	socat -,raw,echo=0,escape=0x0f "UNIX-CONNECT:$socket_path"
fi
echo ''
